spring.datasource.url=${DatabaseURL}
spring.datasource.username=${UserName}
spring.datasource.password=${Password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update